### ISSUE TITLE
Getting error [Errno 2] No such file or directory when I run create_data.sh

### ISSUE THREAD

**Issue by gsg213** [chuanqi305/MobileNet-SSD#182]
When I run create_data.sh, I get this error:

`/home/gus/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=labelmap.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/gus/Documents/SSD_HOME_2/examples/create_lmdb/Dataset/ /home/gus/Documents/SSD_HOME_2/examples/create_lmdb/code/trainval.txt /home/gus/Documents/SSD_HOME_2/examples/create_lmdb/Dataset/Main/lmdb/Main_trainval_lmdb
Traceback (most recent call last):
  File "/home/gus/caffe/scripts/create_annoset.py", line 159, in <module>
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

This directory does not exist `/home/gus/caffe/build/tools/convert_annoset`
It just exists `/home/gus/caffe/build/tools`

In create_data.sh there is cmd, that contains `{}/build/tools/convert_annoset` but I don't know where it should aim, if to a specific file or directory.

**Comment by georgedotai** [comment]
hey there. facing the same problem, you figured it out? 

Basically if you look at line 120 range, there's a variable called "caffe_root", it's probably configured wrong and you can manually set it. I did, but still no luck... :/

**Comment by georgedotai** [comment]
@gsg213 hey friend, did you solve this?

**Comment by funmonty** [comment]
Did you try exporting Caffe root directory in you shell?
